config
zones/allthetropes.org
zones/antiguabarbudacalypso.com
zones/anuwiki.com
zones/miraheze.org
zones/permanentfuturelab.wiki
zones/spiral.wiki

convert weighted DNS to GeoDNS

---

zones/boulderwiki.org

It's been a while since I wrote BIND by hand, but I think I've got this all correct.

Create boulderwiki.org dns

---

zones/takethatwiki.com

Not sure if this is the correct way.

add takethatwiki.com

---

zones/histories.wiki

add histories.wiki zone

---

zones/miraheze.com

Add miraheze.com

---

zones/orain.org

poserdazfreebies subdomain for orain.org

---

zones/scientiawiki.tk

No CAA records since the user wants a CSR and I'm not sure which provider will be used yet.

add scientiawiki.tk zone

---

zones/modelusgov.us

add modelusgov.us zone

---

zones/alwiki.net

add www for alwiki.net

---

.github/ISSUE_REPLY_TEMPLATE.md
.github/ISSUE_TEMPLATE.md

It has issue enabled but no warning.

Add autoresponder, issue template to dns

---

admin_state

Revert "Drain cp5 for upgrade"

---

zones/gtsc.vn
zones/www.schulwiki.de

Partial revert of previous commit

---

zones/miraheze.org

Db2 and db3 are no more and icinga2 is live at icinga.miraheze.org

Cleanup unused servers/subdomains

---

zones/miraheze.org

Please don't merge this, I'll do it myself

Switch piwik/matomo.mh.o to cache proxies

---

zones/miraheze.org

Will be used to evaluate gluster.

Add static-temp to dns

---

config

Revert "Raise timeout to 20s"

---

zones/nonbinary.wiki

Does not migrate pl to use the new cache proxy.

Set nonbinary.wiki and data.nonbinary.wiki to use new cache proxy

---

zones/miraheze.wiki

this was discussed with RhinosF1 and Reception123 via IRC we will have a phab instance

add bots-phab subdomain

---

zones/miraheze.wiki

fix txt record

---

zones/miraheze.wiki

Split bots into a services and servers section (2nd server coming soon)
- Each service may have multiple A records which point to all servers with it's role
- Each server will have 1 A record with it's FQDN under the servers section
Bug: https://phab.bots.miraheze.wiki/T34

tweak DNS config

---

zones/miraheze.wiki

Add tools1

---

zones/miraheze.wiki

This server will shortly be configured to serve static web

Pool tools1 into bots.miraheze.wiki

---

zones/miraheze.wiki

Using phabdigests.bots.miraheze.wiki

Add phabdigests tool

---

zones/tradwiki.org

Revert "tradwiki.org  no longer points to us"

---

zones/miraheze.wiki

This reverts commit 19748e5899e27c35ca2c4e30281aa6e691f18906.

Revert "depool tools1.mh.wiki from bots website DNS (#171)"

---

zones/miraheze.org

RIP ParsoidJs

---

zones/miraheze.wiki

Revert "depool bots1 from rotation"

---

zones/miraheze.org

Miraheze-org: remove record for lists.mh.o

---

zones/trollpasta.com

This should be fine. Not sure if we need to do anything for the CAA section; seems like just an example

Creating zone file for trollpasta.com

---

zones/stardewmodding.wiki

Per [#3765](https://phabricator.mirahez.org/T7365)

Add stardewmodding.wiki zone

---

admin_state

Repool cp3

---

zones/miraheze.org

For ease of docs and stuff, same as for deployment.

mh.org: add mwtask CNAME to active task

---

zones/betaheze.org

[22:38] betaheze: reduce TTL to 10 seconds

---

admin_state

Seems https://github.com/miraheze/puppet/commit/a8748f13682c4ef3c1e3607d58f3c693c5bfd5cc may be helping.
I've had a look at roughly 6hours ago data [0] (which should show the probe being full @ 15s for a while but it matches mostly to cp30 now and teleneting seems much better although I did it during the period where things were better so there's a chance that things may fail later on).
Lets repool and see how things go.
[0] https://grafana.miraheze.org/d/xtkCtBkiz/prometheus-blackbox-exporter?orgId=1&from=now-1h&to=now

Repool cp20/21

---

admin_state

Revert "Repool cp20/21"

---

zones/famedata.org

re-add famedata.org

---

admin_state

Need to deploy a network config change to cp30/31 to allow both to talk to each other again.

Depool ca and repool gb temporarily

---

config

Revert "Depool swiftproxy131"

---

zones/arru.xyz

We migrated from OVH to gandi.

Update MX fields for arru.xyz

---

zones/orain.org

Also cleaning up old challenges at the same time.

Redo ACME challenges for orain.org

---

config

Set tcp_clients_per_thread to 1024

---

zones/pizzatower.wiki

https://issue-tracker.miraheze.org/T12577

T12577: Add _atproto.pizzatower.wiki. DNS record

---

zones/wikitide.net

Reverts miraheze/dns#632
Per @RhinosF1

Revert "Make bastion.wikitide.net use a private ip"

---

zones/otherkin.wiki

T13050: Add _atproto.otherkin.wiki.

---

zones/9b9t.wiki

Revert "Delete zones/9b9t.wiki"
